.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Animator.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Animator.ixx
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/System\&.hpp>\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBanimation::Animator\fP"
.br
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBanimation\fP"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "export module \fBAnimation\fP"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "export module Animation"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
