.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/AnimatedObject.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/AnimatedObject.ixx
.SH SYNOPSIS
.br
.PP
.SS "Funkcje"

.in +1c
.ti -1c
.RI "export void \fBMyFunc\fP ()"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "export module \fBAnimatedObject\fP"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "export void MyFunc ()"

.SH "Dokumentacja zmiennych"
.PP 
.SS "export module AnimatedObject"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
