.TH "Dokumentacja katalogu C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src
.SH SYNOPSIS
.br
.PP
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBAnimatedObject\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBAnimator\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBAssetsManager\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBDemo\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBEffects\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBEngine\&.ixx\fP"
.br
.RI "Plik modułowy zawierający deklarację klasy silnika graficznego\&. "
.ti -1c
.RI "plik \fBErrorHandler\&.ixx\fP"
.br
.RI "Plik modułowy zawierający deklarację klasy \fBErrorHandler\fP\&. "
.ti -1c
.RI "plik \fBGameObjects\&.ixx\fP"
.br
.RI "Plik modułowy zawierający deklaracje klas obiektów graficznych\&. "
.ti -1c
.RI "plik \fBGeneralStuff\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "plik \fBMenu\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBRender\&.ixx\fP"
.br
.ti -1c
.RI "plik \fBSnakeEngine\&.ixx\fP"
.br
.in -1c
