.TH "consts" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
consts
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "constexpr int \fBBOARD_HEIGHT\fP = 12"
.br
.ti -1c
.RI "constexpr int \fBBOARD_WIDTH\fP = 24"
.br
.ti -1c
.RI "constexpr int \fBSTART_X\fP = 200"
.br
.ti -1c
.RI "constexpr int \fBSTART_Y\fP = 120"
.br
.ti -1c
.RI "constexpr int \fBEND_X\fP = \fBSTART_X\fP + (64 * (\fBBOARD_WIDTH\fP \- 1))"
.br
.ti -1c
.RI "constexpr int \fBEND_Y\fP = \fBSTART_Y\fP + (64 * (\fBBOARD_HEIGHT\fP \- 1))"
.br
.ti -1c
.RI "constexpr int \fBROW_SIZE\fP = 64"
.br
.ti -1c
.RI "Color \fBgold\fP = Color(255, 215, 0, 255)"
.br
.ti -1c
.RI "constexpr int \fBSCREEN_WIDTH\fP = 1920"
.br
.ti -1c
.RI "constexpr int \fBSCREEN_HEIGHT\fP = 1080"
.br
.ti -1c
.RI "constexpr float \fBAPPLES_SCALER\fP = 0\&.26f"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "constexpr float consts::APPLES_SCALER = 0\&.26f\fC [constexpr]\fP"

.SS "constexpr int consts::BOARD_HEIGHT = 12\fC [constexpr]\fP"

.SS "constexpr int consts::BOARD_WIDTH = 24\fC [constexpr]\fP"

.SS "constexpr int consts::END_X = \fBSTART_X\fP + (64 * (\fBBOARD_WIDTH\fP \- 1))\fC [constexpr]\fP"

.SS "constexpr int consts::END_Y = \fBSTART_Y\fP + (64 * (\fBBOARD_HEIGHT\fP \- 1))\fC [constexpr]\fP"

.SS "Color consts::gold = Color(255, 215, 0, 255)"

.SS "constexpr int consts::ROW_SIZE = 64\fC [constexpr]\fP"

.SS "constexpr int consts::SCREEN_HEIGHT = 1080\fC [constexpr]\fP"

.SS "constexpr int consts::SCREEN_WIDTH = 1920\fC [constexpr]\fP"

.SS "constexpr int consts::START_X = 200\fC [constexpr]\fP"

.SS "constexpr int consts::START_Y = 120\fC [constexpr]\fP"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
