.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Demo.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Demo.ixx
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <vector>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBassets::ShowCase\fP"
.br
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBassets\fP"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "import \fBRender\fP"
.br
.ti -1c
.RI "import \fBEffects\fP"
.br
.ti -1c
.RI "export module \fBDemo\fP"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "export module Demo"

.SS "import Effects"

.SS "import Render"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
