.TH "directories" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
directories
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "String \fBSPRITES_DIRECTORY\fP = '\&./assets/SpritesTextures/\fBEngine\fP'"
.br
.ti -1c
.RI "String \fBFONTS_DIRECTORY\fP = '\&./assets/Fonts'"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "String directories::FONTS_DIRECTORY = '\&./assets/Fonts'"

.SS "String directories::SPRITES_DIRECTORY = '\&./assets/SpritesTextures/\fBEngine\fP'"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
