.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Effects.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Effects.ixx
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBeffects::Star\fP"
.br
.ti -1c
.RI "class \fBeffects::StarsParticleSystem\fP"
.br
.ti -1c
.RI "class \fBeffects::Snow\fP"
.br
.ti -1c
.RI "class \fBeffects::SnowParticleSystem\fP"
.br
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBeffects\fP"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "export module \fBEffects\fP"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "export module Effects"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
