.TH "effects" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
effects
.SH SYNOPSIS
.br
.PP
.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBSnow\fP"
.br
.ti -1c
.RI "class \fBSnowParticleSystem\fP"
.br
.ti -1c
.RI "class \fBStar\fP"
.br
.ti -1c
.RI "class \fBStarsParticleSystem\fP"
.br
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
