.TH "engineConsts" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
engineConsts
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "constexpr int \fBSCREEN_WIDTH\fP = 1920"
.br
.ti -1c
.RI "constexpr int \fBSCREEN_HEIGHT\fP = 1080"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "constexpr int engineConsts::SCREEN_HEIGHT = 1080\fC [constexpr]\fP"

.SS "constexpr int engineConsts::SCREEN_WIDTH = 1920\fC [constexpr]\fP"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
