.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Engine.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Engine.ixx \- Plik modułowy zawierający deklarację klasy silnika graficznego\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <thread>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBgraphicsEngine::GraphicsEngine\fP"
.br
.RI "Klasa typu singleton odpowiedzialna za inicjacje i wyświetlanie obiektów graficznych, tekstur, obsługi klawiatury i myszki\&. Dodatkowo wyświetla informacje statystyczne\&. "
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBgraphicsEngine\fP"
.br
.RI "Przestrzeń nazw zawierająca definicję klasy silnika graficznego\&. "
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "import \fBDemo\fP"
.br
.ti -1c
.RI "import \fBAnimation\fP"
.br
.ti -1c
.RI "export module \fBEngine\fP"
.br
.ti -1c
.RI "import \fBRender\fP"
.br
.ti -1c
.RI "import \fBGameObjects\fP"
.br
.ti -1c
.RI "import \fBGeneralStuff\fP"
.br
.ti -1c
.RI "import \fBErrorHandler\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik modułowy zawierający deklarację klasy silnika graficznego\&. 


.SH "Dokumentacja zmiennych"
.PP 
.SS "import Animation"

.SS "import Demo"

.SS "export module Engine"

.SS "import \fBErrorHandler\fP"

.SS "import GameObjects"

.SS "import GeneralStuff"

.SS "import Render"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
