.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/ErrorHandler.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/ErrorHandler.ixx \- Plik modułowy zawierający deklarację klasy \fBErrorHandler\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <Windows\&.h>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBErrorHandler\fP"
.br
.RI "Klasa obsługująca błąd window'sowy\&. "
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "export module \fBErrorHandler\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik modułowy zawierający deklarację klasy \fBErrorHandler\fP\&. 


.SH "Dokumentacja zmiennych"
.PP 
.SS "export module \fBErrorHandler\fP"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
