.TH "ErrorHandler" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorHandler \- Klasa obsługująca błąd window'sowy\&.  

.SH SYNOPSIS
.br
.PP
.SS "Statyczne metody publiczne"

.in +1c
.ti -1c
.RI "static void \fBshowErrorDialog\fP (string message, string fileName, string iconType)"
.br
.RI "Metoda statyczna obsługująca błąd lub ostrzeżenie\&. Wyświetla miejsce błędu oraz przekazany przez parametr komunikat\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa obsługująca błąd window'sowy\&. 
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "static void ErrorHandler::showErrorDialog (string message, string fileName, string iconType)\fC [inline]\fP, \fC [static]\fP"

.PP
Metoda statyczna obsługująca błąd lub ostrzeżenie\&. Wyświetla miejsce błędu oraz przekazany przez parametr komunikat\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
