.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/GameObjects.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/GameObjects.ixx \- Plik modułowy zawierający deklaracje klas obiektów graficznych\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBgameObjects::GameObject\fP"
.br
.RI "Klasa opisująca bitmapę\&. Dziedziczy po klasie Sprite, dzięki której posiada metody do transformacji bitmapy\&. "
.ti -1c
.RI "class \fBgameObjects::AnimatedObject\fP"
.br
.RI "Klasa opisująca graficzny obiekt animowany\&. "
.ti -1c
.RI "class \fBgameObjects::Player\fP"
.br
.RI "Klasa gracza, która obsługuje animacje oraz klawiaturę i myszkę\&. "
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBgameObjects\fP"
.br
.RI "Przestrzeń nazw zawierająca definicję klas \fBGameObject\fP, \fBAnimatedObject\fP i \fBPlayer\fP\&. "
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "import \fBGeneralStuff\fP"
.br
.ti -1c
.RI "import \fBErrorHandler\fP"
.br
.ti -1c
.RI "export module \fBGameObjects\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Plik modułowy zawierający deklaracje klas obiektów graficznych\&. 


.SH "Dokumentacja zmiennych"
.PP 
.SS "import \fBErrorHandler\fP"

.SS "export module GameObjects"

.SS "import GeneralStuff"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
