.TH "gameObjects" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gameObjects \- Przestrzeń nazw zawierająca definicję klas \fBGameObject\fP, \fBAnimatedObject\fP i \fBPlayer\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBAnimatedObject\fP"
.br
.RI "Klasa opisująca graficzny obiekt animowany\&. "
.ti -1c
.RI "class \fBGameObject\fP"
.br
.RI "Klasa opisująca bitmapę\&. Dziedziczy po klasie Sprite, dzięki której posiada metody do transformacji bitmapy\&. "
.ti -1c
.RI "class \fBPlayer\fP"
.br
.RI "Klasa gracza, która obsługuje animacje oraz klawiaturę i myszkę\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Przestrzeń nazw zawierająca definicję klas \fBGameObject\fP, \fBAnimatedObject\fP i \fBPlayer\fP\&. 
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
