.TH "globalFunctions" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globalFunctions
.SH SYNOPSIS
.br
.PP
.SS "Funkcje"

.in +1c
.ti -1c
.RI "void \fBgenerate\fP (float &var, int parameter)"
.br
.ti -1c
.RI "bool \fBcollision\fP (Sprite first, Sprite second)"
.br
.ti -1c
.RI "int \fBgenerate\fP (int parameter)"
.br
.ti -1c
.RI "float \fBfindHorizontallyCenteredPositionOfGivenText\fP (String text)"
.br
.ti -1c
.RI "float \fBgetHalfOfSizeOfGivenText\fP (String text)"
.br
.ti -1c
.RI "float \fBgetFullSizeOfGivenText\fP (String text)"
.br
.ti -1c
.RI "Vector2f \fBgetCenterOfTheScreen\fP ()"
.br
.ti -1c
.RI "String \fBgetMusicLevelInText\fP ()"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "bool globalFunctions::collision (Sprite first, Sprite second)"

.SS "float globalFunctions::findHorizontallyCenteredPositionOfGivenText (String text)"

.SS "void globalFunctions::generate (float & var, int parameter)"

.SS "int globalFunctions::generate (int parameter)"

.SS "Vector2f globalFunctions::getCenterOfTheScreen ()"

.SS "float globalFunctions::getFullSizeOfGivenText (String text)"

.SS "float globalFunctions::getHalfOfSizeOfGivenText (String text)"

.SS "String globalFunctions::getMusicLevelInText ()"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
