.TH "globalVars" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globalVars
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "int \fBsnakeSkinNum\fP = 0"
.br
.ti -1c
.RI "int \fBplayerScore\fP = 0"
.br
.ti -1c
.RI "float \fBmusicLevel\fP = 15\&.0f"
.br
.ti -1c
.RI "Vector2f \fBscreenRatio\fP = { 1\&.0f,1\&.0f }"
.br
.ti -1c
.RI "int \fBfontSize\fP = 40"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "int globalVars::fontSize = 40"

.SS "float globalVars::musicLevel = 15\&.0f"

.SS "int globalVars::playerScore = 0"

.SS "Vector2f globalVars::screenRatio = { 1\&.0f,1\&.0f }"

.SS "int globalVars::snakeSkinNum = 0"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
