.TH "graphicsEngine" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphicsEngine \- Przestrzeń nazw zawierająca definicję klasy silnika graficznego\&.  

.SH SYNOPSIS
.br
.PP
.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBGraphicsEngine\fP"
.br
.RI "Klasa typu singleton odpowiedzialna za inicjacje i wyświetlanie obiektów graficznych, tekstur, obsługi klawiatury i myszki\&. Dodatkowo wyświetla informacje statystyczne\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Przestrzeń nazw zawierająca definicję klasy silnika graficznego\&. 
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
