.TH "loadingScreen" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
loadingScreen
.SH SYNOPSIS
.br
.PP
.SS "Funkcje"

.in +1c
.ti -1c
.RI "Vector2u \fBspinnerImages\fP (24, 1)"
.br
.ti -1c
.RI "Vector2f \fBspinnerScale\fP (2\&.0f, 2\&.0f)"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "String \fBspinnerTextureLocation\fP = 'assets/LoadingScreen/spinner\&.png'"
.br
.ti -1c
.RI "String \fBbackgroundTextureLocation\fP = 'assets/LoadingScreen/background\&.jpg'"
.br
.ti -1c
.RI "int \fBnumberOfSpinnerFrames\fP = 24"
.br
.ti -1c
.RI "float \fBspinnerFrameSwitchTime\fP = 1\&.0f / (float)\fBnumberOfSpinnerFrames\fP"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "Vector2u loadingScreen::spinnerImages (24, 1)"

.SS "Vector2f loadingScreen::spinnerScale (2\&. 0f, 2\&. 0f)"

.SH "Dokumentacja zmiennych"
.PP 
.SS "String loadingScreen::backgroundTextureLocation = 'assets/LoadingScreen/background\&.jpg'"

.SS "int loadingScreen::numberOfSpinnerFrames = 24"

.SS "float loadingScreen::spinnerFrameSwitchTime = 1\&.0f / (float)\fBnumberOfSpinnerFrames\fP"

.SS "String loadingScreen::spinnerTextureLocation = 'assets/LoadingScreen/spinner\&.png'"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
