.TH "manager::menuElements" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
manager::menuElements
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "Font \fBfont\fP"
.br
.ti -1c
.RI "Music * \fBmenuSongs\fP"
.br
.ti -1c
.RI "Sound \fBmenuClickSound\fP"
.br
.ti -1c
.RI "SoundBuffer \fBmenuClickSoundBuffer\fP"
.br
.ti -1c
.RI "sf::Texture \fBmenuPointerTexture\fP"
.br
.ti -1c
.RI "Sprite \fBmenuPointerSprite\fP"
.br
.ti -1c
.RI "\fBAnimator\fP * \fBmenuPointerAnimator\fP"
.br
.ti -1c
.RI "sf::Texture \fBmenuBackgroundTexture\fP"
.br
.ti -1c
.RI "Sprite \fBmenuBackgroundSprite\fP"
.br
.ti -1c
.RI "sf::Texture \fBmenuLogoTexture\fP"
.br
.ti -1c
.RI "Sprite \fBmenuLogoSprite\fP"
.br
.ti -1c
.RI "Text * \fBmenuTextButtons\fP"
.br
.ti -1c
.RI "Text * \fBtipsText\fP"
.br
.ti -1c
.RI "Text * \fBstartTextButtons\fP"
.br
.ti -1c
.RI "sf::Texture * \fBoptionsSymbolsTextures\fP"
.br
.ti -1c
.RI "Sprite * \fBoptionsSymbolsSprites\fP"
.br
.ti -1c
.RI "sf::Texture * \fBoptionsButtonsTextures\fP"
.br
.ti -1c
.RI "Sprite * \fBoptionsButtonsSprites\fP"
.br
.ti -1c
.RI "Text * \fBoptionsTextLabels\fP"
.br
.ti -1c
.RI "Text * \fBoptionsTextButtons\fP"
.br
.ti -1c
.RI "Text \fBoptionsMusicLevelText\fP"
.br
.ti -1c
.RI "Text \fBbackButtonText\fP"
.br
.ti -1c
.RI "Text * \fBcreaditsText\fP"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "Text manager::menuElements::backButtonText"

.SS "Text* manager::menuElements::creaditsText"

.SS "Font manager::menuElements::font"

.SS "Sprite manager::menuElements::menuBackgroundSprite"

.SS "sf::Texture manager::menuElements::menuBackgroundTexture"

.SS "Sound manager::menuElements::menuClickSound"

.SS "SoundBuffer manager::menuElements::menuClickSoundBuffer"

.SS "Sprite manager::menuElements::menuLogoSprite"

.SS "sf::Texture manager::menuElements::menuLogoTexture"

.SS "\fBAnimator\fP* manager::menuElements::menuPointerAnimator"

.SS "Sprite manager::menuElements::menuPointerSprite"

.SS "sf::Texture manager::menuElements::menuPointerTexture"

.SS "Music* manager::menuElements::menuSongs"

.SS "Text* manager::menuElements::menuTextButtons"

.SS "Sprite* manager::menuElements::optionsButtonsSprites"

.SS "sf::Texture* manager::menuElements::optionsButtonsTextures"

.SS "Text manager::menuElements::optionsMusicLevelText"

.SS "Sprite* manager::menuElements::optionsSymbolsSprites"

.SS "sf::Texture* manager::menuElements::optionsSymbolsTextures"

.SS "Text* manager::menuElements::optionsTextButtons"

.SS "Text* manager::menuElements::optionsTextLabels"

.SS "Text* manager::menuElements::startTextButtons"

.SS "Text* manager::menuElements::tipsText"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
