.TH "manager::gameLevelsElements" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
manager::gameLevelsElements
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "Font \fBfont\fP"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "Font manager::gameLevelsElements::font"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
