.TH "menuAssets::afterOptions" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menuAssets::afterOptions
.SH SYNOPSIS
.br
.PP
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBsprites\fP"
.br
.in -1c
.SS "Wyliczenia"

.in +1c
.ti -1c
.RI "enum \fBoptionsButtonsIndex\fP { \fBFULLSCREEN\fP, \fBWINDOW\fP, \fBBACK\fP }"
.br
.ti -1c
.RI "enum \fBoptionsTextIndex\fP { \fBCONTROLS\fP, \fBUP\fP, \fBDOWN\fP, \fBRIGHT\fP, \fBLEFT\fP, \fBOPTIONS\fP, \fBMUSIC\fP, \fBSCREEN\fP }"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "String \fBoptionsButtonsText\fP [3] = { 'FULLSCREEN','WINDOWED','\fBBACK\fP' }"
.br
.ti -1c
.RI "Vector2f \fBoptionsButtonsPosition\fP [3]"
.br
.ti -1c
.RI "String \fBoptionsText\fP [8] = {'Controls','Move Up','Move Down','Move Right','Move Left','Options','Music','Screen'}"
.br
.ti -1c
.RI "Vector2f \fBoptionsTextPosition\fP [8]"
.br
.ti -1c
.RI "String \fBoptionsTextSprites\fP [6]"
.br
.ti -1c
.RI "String \fBoptionsMusicLevelInPercent\fP = \fBglobalFunctions::getMusicLevelInText\fP()"
.br
.ti -1c
.RI "Vector2f \fBoptionsMusicLevelInPercentPosition\fP"
.br
.in -1c
.SH "Dokumentacja typów wyliczanych"
.PP 
.SS "enum \fBmenuAssets::afterOptions::optionsButtonsIndex\fP"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fIFULLSCREEN \fP\fP
.TP
\fB\fIWINDOW \fP\fP
.TP
\fB\fIBACK \fP\fP
.SS "enum \fBmenuAssets::afterOptions::optionsTextIndex\fP"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fICONTROLS \fP\fP
.TP
\fB\fIUP \fP\fP
.TP
\fB\fIDOWN \fP\fP
.TP
\fB\fIRIGHT \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fIOPTIONS \fP\fP
.TP
\fB\fIMUSIC \fP\fP
.TP
\fB\fISCREEN \fP\fP
.SH "Dokumentacja zmiennych"
.PP 
.SS "Vector2f menuAssets::afterOptions::optionsButtonsPosition[3]"
\fBWartość początkowa:\fP
.PP
.nf
= { 
            {960\&.0f - globalFunctions::getHalfOfSizeOfGivenText(optionsButtonsText[FULLSCREEN]),backButtonPosition\&.y},
            {1200\&.0f - globalFunctions::getHalfOfSizeOfGivenText(optionsButtonsText[WINDOW]),backButtonPosition\&.y},
            backButtonPosition 
        }
.fi
.SS "String menuAssets::afterOptions::optionsButtonsText[3] = { 'FULLSCREEN','WINDOWED','\fBBACK\fP' }"

.SS "String menuAssets::afterOptions::optionsMusicLevelInPercent = \fBglobalFunctions::getMusicLevelInText\fP()"

.SS "Vector2f menuAssets::afterOptions::optionsMusicLevelInPercentPosition"
\fBWartość początkowa:\fP
.PP
.nf
= {
            1180 - globalFunctions::getHalfOfSizeOfGivenText(optionsMusicLevelInPercent),700\&.0f
        }
.fi
.SS "String menuAssets::afterOptions::optionsText[8] = {'Controls','Move Up','Move Down','Move Right','Move Left','Options','Music','Screen'}"

.SS "Vector2f menuAssets::afterOptions::optionsTextPosition[8]"
\fBWartość początkowa:\fP
.PP
.nf
= {
            {840\&.0f,200\&.0f },
            {840\&.0f,300\&.0f },
            {840\&.0f,350\&.0f },
            {840\&.0f,400\&.0f },
            {840\&.0f,450\&.0f },
            {840\&.0f,550\&.0f },
            {840\&.0f,700\&.0f },
            {840\&.0f,800\&.0f }
        }
.fi
.SS "String menuAssets::afterOptions::optionsTextSprites[6]"
\fBWartość początkowa:\fP
.PP
.nf
= {
            menuHelpersTextures[menuHelpersIndex::CONTROLER],
            menuHelpersTextures[menuHelpersIndex::UP],
            menuHelpersTextures[menuHelpersIndex::DOWN],
            menuHelpersTextures[menuHelpersIndex::RIGHT],
            menuHelpersTextures[menuHelpersIndex::LEFT],
            menuHelpersTextures[menuHelpersIndex::OPTIONS],
        }
.fi
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
