.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Menu.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Menu.ixx
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <SFML/Audio\&.hpp>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBmenu::Menu\fP"
.br
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBmenu\fP"
.br
.in -1c
.SS "Wyliczenia"

.in +1c
.ti -1c
.RI "enum { \fBMAIN\fP, \fBSTART\fP, \fBOPTIONS\fP, \fBCREDITS\fP }"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "import \fBAssetsManager\fP"
.br
.ti -1c
.RI "import \fBAnimation\fP"
.br
.ti -1c
.RI "export module \fBMenu\fP"
.br
.in -1c
.SH "Dokumentacja typów wyliczanych"
.PP 
.SS "anonymous enum"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fIMAIN \fP\fP
.TP
\fB\fISTART \fP\fP
.TP
\fB\fIOPTIONS \fP\fP
.TP
\fB\fICREDITS \fP\fP
.SH "Dokumentacja zmiennych"
.PP 
.SS "import Animation"

.SS "import AssetsManager"

.SS "export module Menu"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
