.TH "music" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
music
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "String \fBlevelsMusicLocation\fP [3]"
.br
.ti -1c
.RI "String \fBmenuMusic\fP [4]"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "String music::levelsMusicLocation[3]"
\fBWartość początkowa:\fP
.PP
.nf
= {
        "assets/Music/level1\&.ogg",
        "assets/Music/level2\&.ogg",
        "assets/Music/level3\&.ogg"
    }
.fi
.SS "String music::menuMusic[4]"
\fBWartość początkowa:\fP
.PP
.nf
= {
        "assets/Music/mainMenu\&.wav",
        "assets/Music/No More Magic\&.ogg",
        "assets/Music/Winds Of Stories\&.ogg",
        "assets/Music/Path to Lake Land\&.ogg"
    }
.fi
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
