.TH "playerMovement" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
playerMovement
.SH SYNOPSIS
.br
.PP
.SS "Wyliczenia"

.in +1c
.ti -1c
.RI "enum \fBdirection\fP { \fBNOTIMPORTANT\fP, \fBLEFT\fP, \fBRIGHT\fP }"
.br
.ti -1c
.RI "enum \fBactions\fP { \fBNEVERMIND\fP, \fBIDLE\fP, \fBWALK\fP, \fBRUN\fP, \fBJUMP\fP }"
.br
.ti -1c
.RI "enum \fBfight\fP { \fBNONE\fP, \fBFIRST\fP, \fBSECOND\fP, \fBTHIRD\fP, \fBJUMPATTACK\fP }"
.br
.in -1c
.SH "Dokumentacja typów wyliczanych"
.PP 
.SS "enum \fBplayerMovement::actions\fP"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fINEVERMIND \fP\fP
.TP
\fB\fIIDLE \fP\fP
.TP
\fB\fIWALK \fP\fP
.TP
\fB\fIRUN \fP\fP
.TP
\fB\fIJUMP \fP\fP
.SS "enum \fBplayerMovement::direction\fP"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fINOTIMPORTANT \fP\fP
.TP
\fB\fILEFT \fP\fP
.TP
\fB\fIRIGHT \fP\fP
.SS "enum \fBplayerMovement::fight\fP"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fINONE \fP\fP
.TP
\fB\fIFIRST \fP\fP
.TP
\fB\fISECOND \fP\fP
.TP
\fB\fITHIRD \fP\fP
.TP
\fB\fIJUMPATTACK \fP\fP
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
