.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Render.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/Render.ixx
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <queue>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBshapes::Point2D\fP"
.br
.ti -1c
.RI "class \fBshapes::LineSegment\fP"
.br
.ti -1c
.RI "class \fBshapes::Circle\fP"
.br
.ti -1c
.RI "class \fBshapes::Polygon\fP"
.br
.ti -1c
.RI "class \fBshapes::PrimitiveRenderer\fP"
.br
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBshapes\fP"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "import \fBEffects\fP"
.br
.ti -1c
.RI "export module \fBRender\fP"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "import Effects"

.SS "export module Render"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
