.TH "shapes::PrimitiveRenderer" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes::PrimitiveRenderer
.SH SYNOPSIS
.br
.PP
.SS "Statyczne metody publiczne"

.in +1c
.ti -1c
.RI "static void \fBdrawPoint\fP (RenderWindow &window, \fBPoint2D\fP point)"
.br
.ti -1c
.RI "static void \fBdrawPoint\fP (RenderWindow &window, \fBPoint2D\fP point, Color color)"
.br
.ti -1c
.RI "static void \fBdrawLine\fP (RenderWindow &window, \fBLineSegment\fP line, Color color)"
.br
.ti -1c
.RI "static void \fBdrawLine\fP (RenderWindow &window, \fBLineSegment\fP line)"
.br
.ti -1c
.RI "static void \fBdrawMulitpleLines\fP (RenderWindow &window, std::vector< \fBLineSegment\fP > lines, Color color)"
.br
.ti -1c
.RI "static void \fBdrawCircle\fP (RenderWindow &window, \fBCircle\fP &circle)"
.br
.ti -1c
.RI "static void \fBdrawPolygon\fP (RenderWindow &window, \fBPolygon\fP polygon)"
.br
.ti -1c
.RI "static void \fBdrawStarParticles\fP (RenderWindow &window, \fBStarsParticleSystem\fP system)"
.br
.ti -1c
.RI "static void \fBdrawSnowParticles\fP (RenderWindow &window, \fBSnowParticleSystem\fP system)"
.br
.ti -1c
.RI "static void \fBdrawStar\fP (RenderWindow &window, \fBStar\fP star)"
.br
.in -1c
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "static void shapes::PrimitiveRenderer::drawCircle (RenderWindow & window, \fBCircle\fP & circle)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawLine (RenderWindow & window, \fBLineSegment\fP line)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawLine (RenderWindow & window, \fBLineSegment\fP line, Color color)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawMulitpleLines (RenderWindow & window, std::vector< \fBLineSegment\fP > lines, Color color)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawPoint (RenderWindow & window, \fBPoint2D\fP point)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawPoint (RenderWindow & window, \fBPoint2D\fP point, Color color)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawPolygon (RenderWindow & window, \fBPolygon\fP polygon)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawSnowParticles (RenderWindow & window, \fBSnowParticleSystem\fP system)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawStar (RenderWindow & window, \fBStar\fP star)\fC [inline]\fP, \fC [static]\fP"

.SS "static void shapes::PrimitiveRenderer::drawStarParticles (RenderWindow & window, \fBStarsParticleSystem\fP system)\fC [inline]\fP, \fC [static]\fP"


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
