.TH "C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/SnakeEngine.ixx" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Chomik/source/repos/SnakeSFMLv1/SnakeSFML/src/SnakeEngine.ixx
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBengine::Engine\fP"
.br
.in -1c
.SS "Przestrzenie nazw"

.in +1c
.ti -1c
.RI " \fBengine\fP"
.br
.in -1c
.SS "Wyliczenia"

.in +1c
.ti -1c
.RI "enum { \fBMENU\fP, \fBGAME\fP }"
.br
.in -1c
.SS "Zmienne"

.in +1c
.ti -1c
.RI "import \fBAssetsManager\fP"
.br
.ti -1c
.RI "import \fBGeneralStuff\fP"
.br
.ti -1c
.RI "import \fBMenu\fP"
.br
.ti -1c
.RI "export module \fBSnakeEngine\fP"
.br
.in -1c
.SH "Dokumentacja typów wyliczanych"
.PP 
.SS "anonymous enum"

.PP
\fBWartości wyliczeń\fP
.in +1c
.TP
\fB\fIMENU \fP\fP
.TP
\fB\fIGAME \fP\fP
.SH "Dokumentacja zmiennych"
.PP 
.SS "import AssetsManager"

.SS "import GeneralStuff"

.SS "import \fBMenu\fP"

.SS "export module SnakeEngine"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
