.TH "sounds" 3 "So, 27 lis 2021" "Silnik graficzny" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sounds
.SH SYNOPSIS
.br
.PP
.SS "Zmienne"

.in +1c
.ti -1c
.RI "String \fBeatingSoundLocation\fP = 'assets/Sounds/appleEaten\&.wav'"
.br
.ti -1c
.RI "String \fBstepsSoundLocation\fP [3]"
.br
.ti -1c
.RI "String \fBsnakeHittingSoundLocation\fP [3]"
.br
.ti -1c
.RI "String \fBmenuClickSound\fP = 'assets/Sounds/misc_menu_2\&.wav'"
.br
.in -1c
.SH "Dokumentacja zmiennych"
.PP 
.SS "String sounds::eatingSoundLocation = 'assets/Sounds/appleEaten\&.wav'"

.SS "String sounds::menuClickSound = 'assets/Sounds/misc_menu_2\&.wav'"

.SS "String sounds::snakeHittingSoundLocation[3]"
\fBWartość początkowa:\fP
.PP
.nf
= {
        "assets/Sounds/rockHitted\&.ogg",
        "assets/Sounds/teleportEntered\&.wav",
        "assets/Sounds/snakeHitted\&.ogg"
    }
.fi
.SS "String sounds::stepsSoundLocation[3]"
\fBWartość początkowa:\fP
.PP
.nf
= {
        "assets/Sounds/stepDirt\&.wav",
        "assets/Sounds/stepSnow\&.wav",
        "assets/Sounds/stepStone\&.wav"
    }
.fi
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Silnik graficzny\&.
